/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Usuarios.java
 *
 * Created on 21/02/2009, 04:00:29 PM
 */

package miCrm.vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import lib.model.miCRM.*;
import miCrm.Fachada;

/**
 *
 * @author Administrator
 */
public class Usuarios extends javax.swing.JFrame {

    /** Creates new form Usuarios */
    public Usuarios() {
        initComponents();
        cargarListas();
    }

  private void cargarDatos(Usuario u) {
    tId.setText(u.getId().toString());
    tId.setEnabled(false);
    tNombre.setText(u.getNombre());
    tPassword.setText("");
    tRepetir.setText("");
    cGrupo.setSelectedItem(u.getGrupo());
  }
  private void limpiarCampos() {
    tId.setText("");
    tId.setEnabled(true);
    tNombre.setText("");
    tPassword.setText("");
    tRepetir.setText("");
    cGrupo.setSelectedItem(null);
    cargarListas();
  }
  private boolean validarCampos() {
    if (tPassword.getPassword().length!=tRepetir.getPassword().length) {
      JOptionPane.showMessageDialog(
        null,"La constraseña no coincide con la verificación",
        "Error al guardar",
        JOptionPane.ERROR_MESSAGE);
      return false;
    }
    for (int i = 0; i < tPassword.getPassword().length; i++) {
      if (tPassword.getPassword()[i]!=tRepetir.getPassword()[i]) {
        JOptionPane.showMessageDialog(
          null,"La constraseña no coincide con la verificación",
          "Error al guardar",
          JOptionPane.ERROR_MESSAGE);
        return false;
      }
    }
    if ((tPassword.getPassword().toString().length()<4) && (tPassword.getPassword().toString().length()>0)) {
      JOptionPane.showMessageDialog(
        null,"La constraseña debe teneral menos 4 caracteres",
        "Error al guardar",
        JOptionPane.ERROR_MESSAGE);
      return false;
    }
    if ((tPassword.getPassword().toString().length()==0) && (tId.isEnabled())) {
      JOptionPane.showMessageDialog(
        null,"La constraseña no puede estar vacía para un nuevo usuario",
        "Error al guardar",
        JOptionPane.ERROR_MESSAGE);
      return false;
    }
    if (cGrupo.getSelectedIndex()==-1) {
      JOptionPane.showMessageDialog(
        null,"Debe elegir un grupo para el usuario",
        "Error al guardar",
        JOptionPane.ERROR_MESSAGE);
      return false;
    }
    return true;
  }
  private void cargarListas() {
    listaUsuarios.clear();
    for (Usuario u : Fachada.listarUsuarios()) {
      listaUsuarios.addElement(u);
    }
    cGrupo.removeAllItems();
    for (Grupo g : Fachada.listarGrupos()) {
      cGrupo.addItem(g);
    }
  }
  private boolean guardarDatos(Usuario u) {
    try {
      if (u==null) {
        u = new Usuario();
        u.setId(Integer.parseInt(tId.getText()));
      }
      u.setNombre(tNombre.getText());
      if (tPassword.getPassword().length>=4) {
        u.setPassword(tPassword.getPassword());
      }
      u.setGrupo((Grupo) cGrupo.getSelectedItem());
      if (Fachada.guardarUsuario(u)) {
        return true;
      }
      else {
        return false;
      }
    } catch (Exception e) {
      return false;
    }
  }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelABM = new javax.swing.JSplitPane();
    panelEditar = new javax.swing.JPanel();
    lId = new javax.swing.JLabel();
    tId = new javax.swing.JTextField();
    tNombre = new javax.swing.JTextField();
    lNombre = new javax.swing.JLabel();
    lClave = new javax.swing.JLabel();
    lRepetir = new javax.swing.JLabel();
    lGrupo = new javax.swing.JLabel();
    cGrupo = new javax.swing.JComboBox();
    tRepetir = new javax.swing.JPasswordField();
    tPassword = new javax.swing.JPasswordField();
    bGuardar = new javax.swing.JButton();
    bEliminar = new javax.swing.JButton();
    bCerrar = new javax.swing.JButton();
    bNuevo = new javax.swing.JButton();
    panelListado = new javax.swing.JScrollPane();
    listaUsuarios = new DefaultListModel();
    jListado = new javax.swing.JList(listaUsuarios);

    setTitle("Usuarios");

    panelABM.setDividerLocation(150);

    panelEditar.setMinimumSize(new java.awt.Dimension(160, 160));

    lId.setText("Id");

    lNombre.setText("Nombre");

    lClave.setText("Clave");

    lRepetir.setText("Repetir");

    lGrupo.setText("Grupo");

    bGuardar.setText("Guardar");
    bGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bGuardarActionPerformed(evt);
      }
    });

    bEliminar.setText("Eliminar");
    bEliminar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bEliminarActionPerformed(evt);
      }
    });

    bCerrar.setText("Cerrar");
    bCerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bCerrarActionPerformed(evt);
      }
    });

    bNuevo.setText("Nuevo");
    bNuevo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bNuevoActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
    panelEditar.setLayout(panelEditarLayout);
    panelEditarLayout.setHorizontalGroup(
      panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEditarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(panelEditarLayout.createSequentialGroup()
              .addComponent(lId)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelEditarLayout.createSequentialGroup()
              .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lNombre)
                .addComponent(lGrupo)
                .addComponent(lRepetir)
                .addComponent(lClave))
              .addGap(30, 30, 30)
              .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(tPassword)
                .addComponent(tRepetir)
                .addComponent(cGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
          .addGroup(panelEditarLayout.createSequentialGroup()
            .addComponent(bNuevo)
            .addGap(18, 18, 18)
            .addComponent(bGuardar)
            .addGap(18, 18, 18)
            .addComponent(bEliminar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
            .addComponent(bCerrar)))
        .addContainerGap())
    );
    panelEditarLayout.setVerticalGroup(
      panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEditarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lId)
          .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lNombre)
          .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lClave)
          .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lRepetir)
          .addComponent(tRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lGrupo)
          .addComponent(cGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bCerrar)
          .addComponent(bNuevo)
          .addComponent(bGuardar)
          .addComponent(bEliminar))
        .addContainerGap())
    );

    panelABM.setRightComponent(panelEditar);

    panelListado.setMinimumSize(new java.awt.Dimension(80, 80));
    panelListado.setPreferredSize(new java.awt.Dimension(80, 160));

    jListado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jListado.setMinimumSize(new java.awt.Dimension(80, 160));
    jListado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        jListadoValueChanged(evt);
      }
    });
    panelListado.setViewportView(jListado);

    panelABM.setLeftComponent(panelListado);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelABM, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelABM, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
      try {
        if (!validarCampos()) {
          return;
        }
        Usuario unUsuario = Fachada.buscarUsuarioPorId(Integer.parseInt(tId.getText()));
        if(tId.isEnabled()) {
          if (unUsuario!=null) {
            if (JOptionPane.showConfirmDialog(
              null,"El usuario con ID "+tId.getText()+" ya existe ("+unUsuario.toString()+"). Deseea reemplazarlo?",
              "Confirma reemplazar?",
              JOptionPane.YES_NO_OPTION)==JOptionPane.NO_OPTION) {
                return;
            }
          }
        }
        if (!guardarDatos(unUsuario)) {
          throw new Exception("falló guardarDatos(unUsuario)");
        }
        else {
          JOptionPane.showMessageDialog(
              null,"Usuario guardado",
              "Usuario guardado",
              JOptionPane.INFORMATION_MESSAGE);
        }
        limpiarCampos();
      } catch (Exception e) {
        System.out.println(e.toString());
        JOptionPane.showMessageDialog(
              null,"Error al guardar el usuario. Verifique los datos.\r\n"+
              "Si el error persiste, por favor consulte con el administrador.\r\n"
              +e.toString(),
              "Error al guardar",
              JOptionPane.ERROR_MESSAGE);
      }

}//GEN-LAST:event_bGuardarActionPerformed

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
      limpiarCampos();
    }//GEN-LAST:event_bNuevoActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
      try {
        Usuario unUsuario = Fachada.buscarUsuarioPorId(Integer.parseInt(tId.getText()));
        if (unUsuario==null) {
          throw new Exception("No existe usuario con ID = "+tId.getText());
        }
        if (!Fachada.borrarUsuario(unUsuario)) {
          throw new Exception("Falló borrarUsuario(unUsuario)");
        }
        else {
          JOptionPane.showMessageDialog(
              null,"El usuario "+unUsuario.toString()+" fue eliminado",
              "Usuario Eliminado",
              JOptionPane.INFORMATION_MESSAGE);
          limpiarCampos();
        }
      } catch (Exception e) {
        System.out.println(e.toString());
        JOptionPane.showMessageDialog(
              null,"Error al eliminar el usuario. Verifique los datos.\r\n"+
              "Si el error persiste, por favor consulte con el administrador.\r\n"
              +e.toString(),
              "Error al eliminar",
              JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void jListadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListadoValueChanged
      if (jListado.getSelectedIndex()!=-1) {
        cargarDatos((Usuario) jListado.getSelectedValue());
      }
}//GEN-LAST:event_jListadoValueChanged

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
      this.dispose();
    }//GEN-LAST:event_bCerrarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bCerrar;
  private javax.swing.JButton bEliminar;
  private javax.swing.JButton bGuardar;
  private javax.swing.JButton bNuevo;
  private javax.swing.JComboBox cGrupo;
  private javax.swing.JList jListado;
  private javax.swing.JLabel lClave;
  private javax.swing.JLabel lGrupo;
  private javax.swing.JLabel lId;
  private javax.swing.JLabel lNombre;
  private javax.swing.JLabel lRepetir;
  private javax.swing.JSplitPane panelABM;
  private javax.swing.JPanel panelEditar;
  private javax.swing.JScrollPane panelListado;
  private javax.swing.JTextField tId;
  private javax.swing.JTextField tNombre;
  private javax.swing.JPasswordField tPassword;
  private javax.swing.JPasswordField tRepetir;
  // End of variables declaration//GEN-END:variables
  private javax.swing.DefaultListModel listaUsuarios;


}
